#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE
#WARNING!!! THE FOLLOWING LINES CONTAIN EXPLICIT LANGUAGE

BadWords = [
    "nigger",
    "nigga",
    "niggers",
    "niggas",
    "niggs",
    "niger",
    "faggot",
    "fag",
    "nigg",
    "nig",
    "sex",
    " cp ",
    "child",
    "porn",
    "dick",
    "penis",
    "nig/ger",
    "nig/ga",
    " rape ",
    "retard",
    "retarded",
    "retards",
    "isis",
    "allahu",
    "akbar",
    "besatiality",
    "buttfuck",
    "circlejerk",
    "cum",
    "cummer",
    "cumming",
    "cumshot",
    "dicks",
    "dildo",
    "ejaculating",
    "ejaculation",
    "ejaculat",
    "fuk",
    "gangbang",
    "gay",
    "horny",
    "pussy",
    "vagina",
    "jackoff",
    " kkk ",
    "jizz",
    " kum ",
    "molest",
    "molester",
    "pedo",
    "pedophile",
    "pissing",
    "piss",
    "pornography",
    "sperm",
    "cock",
    "69420",
    "6969",
    "69 69",
    " 420 ",
    "hentai",
    "yaoi",
    "protogen",
    "furry",
    "boobs",
    "boob",
    "nipples",
    "nipple",
    "negro",
    "n1gg3r",
    ".ct8",
    "ct8",
    ".pl",
    "hitler",
    "borderhopper",
    "border hopper",
    "nigar",
    "perro hijueputa",
    "wea",
    "que wea",
    "https://pornhub.com",
    "pornhub.com",
    "buttplug",
    "minor",
    "are you a minor",
    "cozol",
    "child porn",
    "i like watching csam",
    "i like child porn",
    "subter sucks",
    "i like grooming children",
    "yeah2",
    "yeahtwos",
    "egg",
    "nut",
    "kys",
    "killyourself",
    "kill yourself",
    "ku klux klan",
    "raped",
    "ra.pe",
    "r.ape",
    "r.ap.e",
    "rapist",
    "rap.ist",
    "r.apist",
    "r.a.p.i.s.t",
    "ra.pist",
    "rap.ist",
    "rapi.st",
    "rapis.t",
    "ra.p.ist",
    "k.ys",
    "ky.s",
    "k.y.s",
    " homosexual ", #!!!!!!!!!!! literally homophobic!!!!!!!!
    "discord.gg/",
    ".gg/austiverse", #austiblox invite
    ".gg/kamari", #shitty hexagon
    ".gg/",
    "g.ay",
    "ga.y",
    "g.a.y",
    "ga.y",
    ".com",
    ".net",
    ".org",
    ".zip",
    ".rocks",
    ".io",
    "austiblox.net",
    "kamari.zip",
    "reddit.com", #kiddos post random stuff sometimes
    "drive.google.com"
]

ExtendedBadWords = [
    "fuck",
    "fucking",
    "fucks",
    "shit",
    "horny",
    " fu.ck ",
    " fuc.k ",
    " f.u.c.k ",
    " f.uck "
]
